# Generated by Django 3.2.18 on 2023-09-08 19:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20230609_1503'),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscribePageSegmentPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('checked_by_default', models.BooleanField(default=False, help_text='If selected, this list will be checked when the subscribe page loads.')),
                ('display_name', models.TextField(blank=True, default='', help_text='The name here will be used instead of the default name for this list.')),
                ('mailing_list_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subscribe.mailinglistsegment')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_placements', to='home.subscribepage')),
            ],
            options={
                'verbose_name': 'mailing list segment placement',
                'verbose_name_plural': 'mailing list segment placements',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='subscribepagesegmentplacement',
            constraint=models.UniqueConstraint(fields=('page', 'mailing_list_segment'), name='unique_list_page'),
        ),
    ]
