# Generated by Django 3.2.18 on 2023-09-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_mailing_list_segment_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglistsegment',
            options={'permissions': [('can_sync_from_campaign_monitor', 'Can sync from Campaign Monitor')]},
        ),
    ]
