# Generated by Django 3.2.18 on 2023-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_remove_legacy_subscribe_page_models'),
        ('home', '0062_remove_legacy_subscribe_page_models'),
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('subscribe', '0003_alter_mailinglistsegment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionsegment',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='SubscribePage',
        ),
        migrations.DeleteModel(
            name='SubscriptionSegment',
        ),
    ]
