# Generated by Django 3.2.18 on 2023-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscribepagesegmentplacement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribepagesegmentplacement',
            constraint=models.UniqueConstraint(
                fields=('page', 'mailing_list_segment'), name='unique_list_page'
            ),
        ),
    ]
