# Generated by Django 3.2.18 on 2024-09-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_remove_legacy_subscribe_page_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglistsegment',
            options={'permissions': [('can_sync_from_mailchimp', 'Can sync from Mailchimp')]},
        ),
    ]
