version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://wagtail:test@db:5432/wagtail
        USERID: ${UID:?err}
    command:
      - /bin/sh
      - '-c'
      - 'entrypoint.sh'
    volumes:
      - ./:/app
      - type: bind
        source: ${HOME}/.netrc
        target: /home/wagtail/.netrc
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://wagtail:test@db:5432/wagtail
      SECRET_KEY: test
      DJANGO_SETTINGS_MODULE: newamericadotorg.settings.dev
      ELASTICSEARCH_URL: http://es:9200
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - es
    working_dir: /app
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: test
    restart: always
    ports:
      - "5432:5432"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - script.inline=true
      - script.search=true
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 2g
    expose:
      - "9200"

  redis:
    image: "redis:alpine"
    command: redis-server
    expose:
     - "6379"
