# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20170721_0946'),
        ('home', '0024_location'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTopicRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='home.Post')),
            ],
        ),
        migrations.AlterModelOptions(
            name='issueortopic',
            options={'verbose_name': 'Topic'},
        ),
        migrations.AddField(
            model_name='issueortopic',
            name='parent_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='posttopicrelationship',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issue.IssueOrTopic'),
        ),
    ]
