# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('programs', '0003_auto_20170721_0946'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Topics',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='issueortopic',
            options={'verbose_name': 'Topic'},
        ),
        migrations.AddField(
            model_name='issueortopic',
            name='parent_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='programs.Program'),
        ),
    ]
