# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('issue', '0002_auto_20170725_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Topics',
            },
            bases=('wagtailcore.page',),
        ),
    ]
