# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20170712_1241'),
        ('issue', '0003_topichomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTopicRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='person.Person')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issue.IssueOrTopic')),
            ],
        ),
    ]
