# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_persontopicrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttopicrelationship',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttopicrelationship',
            name='topic',
        ),
        migrations.DeleteModel(
            name='PostTopicRelationship',
        ),
    ]
