# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20170725_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persontopicrelationship',
            name='person',
        ),
        migrations.RemoveField(
            model_name='persontopicrelationship',
            name='topic',
        ),
        migrations.DeleteModel(
            name='PersonTopicRelationship',
        ),
    ]
