# Generated by Django 3.0.11 on 2021-04-22 16:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0055_auto_20210208_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBriefsHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Homepage for all briefs',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
                ('attachment', wagtail.fields.StreamField([('attachment', wagtail.documents.blocks.DocumentChooserBlock(null=True, required=False))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.post',),
        ),
        migrations.CreateModel(
            name='ProgramBriefsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Briefs Homepage',
            },
            bases=('wagtailcore.page',),
        ),
    ]
