# Generated by Django 3.0.11 on 2021-04-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allbriefshomepage',
            options={'verbose_name': 'Homepage for all Briefs'},
        ),
    ]
