# Generated by Django 3.2.18 on 2023-04-21 21:15

from django.db import migrations
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0002_auto_20210429_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='attachment',
            field=wagtail.fields.StreamField([('attachment', wagtail.documents.blocks.DocumentChooserBlock(null=True, required=False))], blank=True, null=True, use_json_field=True),
        ),
    ]
