# Generated by Django 3.0.11 on 2021-05-28 01:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='events_list',
            field=wagtail.fields.StreamField([('event', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['event.Event'], required=True)), ('title', wagtail.blocks.CharBlock(label='Override title', required=False)), ('description', wagtail.blocks.CharBlock(label='Override description text', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Override image', required=False))], icon='date', label='Event'))], blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='programs_list',
            field=wagtail.fields.StreamField([('program', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['programs.Program', 'programs.Subprogram'], required=True)), ('description', wagtail.blocks.CharBlock(label='Override description text', required=False))], icon='doc-empty', label='Program'))], blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='publications_list',
            field=wagtail.fields.StreamField([('publication', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['home.Post'], required=True)), ('title', wagtail.blocks.CharBlock(label='Override title', required=False)), ('description', wagtail.blocks.CharBlock(label='Override description text', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Override image', required=False))], icon='doc-empty', label='Publication'))], blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='resources_list',
            field=wagtail.fields.StreamField([('external_resource', wagtail.blocks.StructBlock([('link', wagtail.blocks.URLBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=False)), ('program', wagtail.blocks.CharBlock(label='Program (shows below description, with resource type)', required=False)), ('resource_type', wagtail.blocks.CharBlock(label='Resource type, e.g., "External Link" (shows below description, with Program', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False))], icon='link', label='External resource')), ('attachment', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(label='Override document title', required=False)), ('description', wagtail.blocks.CharBlock(required=False)), ('program', wagtail.blocks.CharBlock(label='Program (shows below description, with resource type)', required=False)), ('resource_type', wagtail.blocks.CharBlock(label='Resource type, e.g., "Document" (shows below description, with Program)', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False))], icon='doc-full', label='Attachment'))], blank=True),
        ),
    ]
