# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20160614_1858'),
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInDepthHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('story_excerpt', models.CharField(blank=True, max_length=140, null=True)),
                ('story_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'verbose_name': 'Homepage for all In-Depth Projects',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InDepthProject',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
                ('buttons', wagtail.wagtailcore.fields.StreamField([('button', wagtail.wagtailcore.blocks.StructBlock([('button_text', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=True)), ('button_url', wagtail.wagtailcore.blocks.URLBlock(default='https://www.', required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'In-Depth Project',
            },
            bases=('home.post',),
        ),
        migrations.CreateModel(
            name='InDepthSection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subheading', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('generate_title_panel', models.BooleanField(default=False, help_text='Will create a title panel before the first panel if checked')),
                ('panels', wagtail.wagtailcore.fields.StreamField([('panel', wagtail.wagtailcore.blocks.StructBlock([('panel_title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('panel_color_theme', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'White'), ('grey', 'Grey'), ('black', 'Black')])), ('panel_body', wagtail.wagtailcore.blocks.StreamBlock([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'button', wagtail.wagtailcore.blocks.StructBlock([(b'button_text', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=True)), (b'button_link', wagtail.wagtailcore.blocks.URLBlock(default=b'https://www.', required=True)), (b'alignment', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'left-aligned', b'Left'), (b'center-aligned', b'Center')]))])), (b'iframe', wagtail.wagtailcore.blocks.StructBlock([(b'source_url', wagtail.wagtailcore.blocks.URLBlock(required=True)), (b'width', home.blocks.IntegerBlock(help_text=b'The maximum possible iframe width is 1050', max_value=1050)), (b'height', home.blocks.IntegerBlock())]))]))]))], blank=True, null=True)),
                ('story_excerpt', models.CharField(blank=True, max_length=140, null=True)),
                ('story_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'verbose_name': 'In-Depth Project Section',
            },
            bases=('wagtailcore.page',),
        ),
    ]
