# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_depth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indepthproject',
            name='project_logo_link',
            field=models.URLField(blank=True, max_length=140, null=True),
        ),
    ]
