# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160614_1858'),
        ('in_depth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indepthproject',
            name='project_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
