# Generated by Django 3.2.18 on 2023-05-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_depth', '0033_auto_20230421_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='allindepthhomepage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='indepthproject',
            name='project_logo_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Project logo alternative text'),
        ),
        migrations.AddField(
            model_name='indepthsection',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
    ]
