# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 01:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('press_release', '0002_auto_20160108_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='attachment',
            field=wagtail.wagtailcore.fields.StreamField((('attachment', wagtail.wagtaildocs.blocks.DocumentChooserBlock(null=True, required=False)),)),
        ),
    ]
