# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_release', '0003_auto_20160210_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressrelease',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='pressrelease',
            name='sub_headline',
        ),
    ]
