# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_release', '0004_auto_20160328_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpressreleasespage',
            options={'verbose_name': 'Press Release Homepage for Program and Subprograms'},
        ),
    ]
