# Generated by Django 3.2.18 on 2025-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_release', '0006_alter_pressrelease_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='archived_page',
            field=models.BooleanField(default=False, verbose_name='Archived Page'),
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='last_updated',
            field=models.TextField(blank=True, help_text='Enter in the month and year this page was last updated (Example: April 2022).', null=True),
        ),
    ]
