# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_source_word_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='overwrite_sections_on_save',
            field=models.BooleanField(default=False, help_text=b'If checked, sections and endnote fields will be overwritten with Word document source on save. Use with CAUTION!'),
        ),
        migrations.AlterField(
            model_name='report',
            name='endnotes',
            field=wagtail.wagtailcore.fields.StreamField([(b'endnote', wagtail.wagtailcore.blocks.StructBlock([(b'number', wagtail.wagtailcore.blocks.TextBlock()), (b'note', wagtail.wagtailcore.blocks.RichTextBlock())]))]),
        ),
    ]
