# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20180425_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dataviz_src',
            field=models.CharField(blank=True, help_text=b'', max_length=300, null=True),
        ),
    ]
