# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20181016_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='publication_cover_image',
        ),
    ]
