# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_add_datawrapper_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='theme_full_bleed',
            field=models.BooleanField(default=False, help_text='Display bleed image on landing page'),
        ),
    ]
