# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0025_auto_20170728_1418'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContentType',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
            ],
            options={
                'verbose_name': 'Custom',
            },
            bases=('home.post',),
        ),
        migrations.CreateModel(
            name='CustomContentTypeCategory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Category',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramCustomContentTypePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subheading', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('story_excerpt', models.CharField(blank=True, max_length=500, null=True)),
                ('story_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'verbose_name': 'Custom Content Homepage',
            },
            bases=('wagtailcore.page',),
        ),
    ]
