# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0030_auto_20180226_0804'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOtherPostsHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Homepage for all Other Posts',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OtherPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
                ('attachment', wagtail.core.fields.StreamField([(b'attachment', wagtail.documents.blocks.DocumentChooserBlock(required=False))], null=True)),
            ],
            options={
                'verbose_name': 'Other Post',
            },
            bases=('home.post',),
        ),
        migrations.CreateModel(
            name='OtherPostCategory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Category',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramOtherPostsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('singular_title', models.CharField(max_length=255)),
                ('subheading', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('story_excerpt', models.CharField(blank=True, max_length=500, null=True)),
                ('story_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'verbose_name': 'Homepage for Other Posts Program and Subprograms',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='otherpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='other_content.OtherPostCategory'),
        ),
        migrations.AddField(
            model_name='otherpost',
            name='other_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='other_content.ProgramOtherPostsPage'),
        ),
    ]
