# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-02 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allotherpostshomepage',
            options={'verbose_name': 'Other Posts Homepage'},
        ),
    ]
