# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-25 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0002_auto_20180402_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programotherpostspage',
            options={'verbose_name': 'Other Posts Homepage'},
        ),
    ]
