# Generated by Django 3.2.18 on 2025-02-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0009_add_header_footer_toggle_to_full_page_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullpageembed',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
