# Generated by Django 3.2.18 on 2025-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0010_add_subheading_to_embed_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpost',
            name='archived_page',
            field=models.BooleanField(default=False, verbose_name='Is this Page Archived?'),
        ),
    ]
