# Generated by Django 3.2.18 on 2025-05-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0011_otherpost_archived_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpost',
            name='last_updated',
            field=models.TextField(blank=True, help_text='Enter in the month and year this page was last updated (Example: April 2022).', null=True),
        ),
        migrations.AlterField(
            model_name='otherpost',
            name='archived_page',
            field=models.BooleanField(default=False, verbose_name='Archived Page'),
        ),
    ]
