# Generated by Django 3.2.18 on 2025-08-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0012_auto_20250507_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherpost',
            options={'permissions': [('can_add_otherpostpage', 'Can add Other Post page')], 'verbose_name': 'Other Post'},
        ),
    ]
