# Generated by Django 3.2.18 on 2025-10-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0013_alter_otherpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherpost',
            options={'verbose_name': 'Other Post'},
        ),
    ]
