# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='invitation_only',
            field=models.BooleanField(default=False),
        ),
    ]
