# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 16:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_invitation_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='speakers',
            field=wagtail.fields.StreamField([(b'person', wagtail.blocks.StructBlock([(b'name', wagtail.blocks.TextBlock(required=True)), (b'title', wagtail.blocks.TextBlock()), (b'description', wagtail.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock(icon=b'image', required=False)), (b'twitter', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
    ]
