# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20161128_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='publish_sessions',
            field=models.BooleanField(default=False, help_text=b'Sessions list will not show up until this is checked.'),
        ),
        migrations.AddField(
            model_name='conference',
            name='publish_speakers',
            field=models.BooleanField(default=False, help_text=b'Speakers list will not show up until this is checked.'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='invitation_only',
            field=models.BooleanField(default=False, help_text=b'This will override the RSVP link and replace it with an request for invitation'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='partners',
            field=wagtail.core.fields.StreamField([(b'partner', wagtail.core.blocks.StructBlock([(b'name', wagtail.core.blocks.TextBlock()), (b'type', wagtail.core.blocks.ChoiceBlock(choices=[(b'premier_sponsor', b'Premier Sponsor'), (b'sponsor', b'Sponsor'), (b'media_partner', b'Media Partner'), (b'recognized_partner', b'Recognized Partner')])), (b'logo', wagtail.images.blocks.ImageChooserBlock(icon=b'image', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sessions',
            field=wagtail.core.fields.StreamField([(b'days', wagtail.core.blocks.StructBlock([(b'day', wagtail.core.blocks.ChoiceBlock(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6')], help_text=b'What day of the conference is this session on?', required=False)), (b'start_time', wagtail.core.blocks.TimeBlock(required=False)), (b'end_time', wagtail.core.blocks.TimeBlock(required=False)), (b'sessions', wagtail.core.blocks.StreamBlock([(b'session', wagtail.core.blocks.StructBlock([(b'name', wagtail.core.blocks.TextBlock()), (b'session_type', wagtail.core.blocks.ChoiceBlock(choices=[(b'panel', b'Panel'), (b'lecture', b'Lecture'), (b'break', b'Break'), (b'meal', b'Meal'), (b'reception', b'Reception'), (b'registration', b'Registration')])), (b'description', wagtail.core.blocks.RichTextBlock(required=False)), (b'start_time', wagtail.core.blocks.TimeBlock(required=False)), (b'end_time', wagtail.core.blocks.TimeBlock(required=False)), (b'speakers', wagtail.core.blocks.StreamBlock([(b'speaker', wagtail.core.blocks.StructBlock([(b'name', wagtail.core.blocks.TextBlock(required=True)), (b'title', wagtail.core.blocks.TextBlock(required=False))]))])), (b'archived_video_link', wagtail.core.blocks.URLBlock(help_text=b'Enter youtube link after conference', required=False))]))]))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='speakers',
            field=wagtail.core.fields.StreamField([(b'person', wagtail.core.blocks.StructBlock([(b'name', wagtail.core.blocks.TextBlock(required=True)), (b'title', wagtail.core.blocks.TextBlock(required=False)), (b'description', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock(icon=b'image', required=False)), (b'twitter', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
    ]
