# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20161207_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='invitation_only',
            field=models.BooleanField(default=False, help_text=b'This will override the RSVP link and replace it with an request for invitation'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publish_sessions',
            field=models.BooleanField(default=False, help_text=b'Sessions list will not show up until this is checked.'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publish_speakers',
            field=models.BooleanField(default=False, help_text=b'Speakers list will not show up until this is checked.'),
        ),
    ]
