# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20170209_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='live_stream',
            field=models.URLField(blank=True, null=True),
        ),
    ]
