# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_conference_live_stream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Conference'},
        ),
    ]
