# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 16:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20170407_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='hotel_details',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'must be filled for header and section to appear', null=True),
        ),
    ]
