# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20180327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='About Image'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='alternate_logo',
            field=models.ForeignKey(blank=True, help_text='This will replace the New America logo at the top of the introduction / cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='Alternate Logo'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.TextField(blank=True, default='Washington', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='This will be the ABOUT text'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='directions',
            field=wagtail.wagtailcore.fields.StreamField((('direction', wagtail.wagtailcore.blocks.StructBlock((('transportation_type', wagtail.wagtailcore.blocks.CharBlock(help_text='e.g car, metro, taxi')), ('directions', wagtail.wagtailcore.blocks.RichTextBlock())))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='host_organization',
            field=models.TextField(blank=True, default='New America', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hotel_city',
            field=models.TextField(blank=True, default='Washington', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hotel_details',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='must be filled for header and section to appear', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hotel_location_name',
            field=models.TextField(blank=True, help_text='Name of building (e.g. the Kennedy Center)', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hotel_state',
            field=models.TextField(blank=True, default='D.C.', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hotel_street',
            field=models.TextField(blank=True, default='740 15th St NW #900', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hotel_zipcode',
            field=models.TextField(blank=True, default='20005', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='invitation_only',
            field=models.BooleanField(default=False, help_text='This will override the RSVP link and replace it with an request for invitation'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location_name',
            field=models.TextField(blank=True, help_text='Name of building (e.g. the Kennedy Center)', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='partner_heading',
            field=models.TextField(default='Sponsors & Partners'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='partners',
            field=wagtail.wagtailcore.fields.StreamField((('partner', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.TextBlock()), ('type', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('no_type', 'None'), ('premier_sponsor', 'Premier Sponsor'), ('sponsor', 'Sponsor'), ('media_partner', 'Media Partner'), ('recognized_partner', 'Recognized Partner')])), ('logo', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', required=False))))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publish_sessions',
            field=models.BooleanField(default=False, help_text='Sessions list will not show up until this is checked.'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publish_speakers',
            field=models.BooleanField(default=False, help_text='Speakers list will not show up until this is checked.'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sessions',
            field=wagtail.wagtailcore.fields.StreamField((('days', wagtail.wagtailcore.blocks.StructBlock((('collapsible', wagtail.wagtailcore.blocks.BooleanBlock(default=True, help_text='Allow schedule sessions to expand and collapse', required=False)), ('day', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], help_text='What day of the conference is this session on?', required=False)), ('start_time', wagtail.wagtailcore.blocks.TimeBlock(required=False)), ('end_time', wagtail.wagtailcore.blocks.TimeBlock(required=False)), ('sessions', wagtail.wagtailcore.blocks.StreamBlock((('session', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.TextBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('start_time', wagtail.wagtailcore.blocks.TimeBlock(required=False)), ('end_time', wagtail.wagtailcore.blocks.TimeBlock(required=False)), ('speakers', wagtail.wagtailcore.blocks.StreamBlock((('speaker', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('twitter', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('title', wagtail.wagtailcore.blocks.TextBlock(required=False))))),))), ('archived_video_link', wagtail.wagtailcore.blocks.URLBlock(help_text='Enter youtube link after conference', required=False))))),)))), help_text='for multi-day events')),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='speakers',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.TextBlock(required=False)), ('person', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('title', wagtail.wagtailcore.blocks.TextBlock(help_text='125 character limit', max_length=125, required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', required=False)), ('twitter', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='state',
            field=models.TextField(blank=True, default='D.C.', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='story_excerpt',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='street',
            field=models.TextField(blank=True, default='740 15th St NW #900', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='venue',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('columns', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.RichTextBlock()), ('right_column', wagtail.wagtailcore.blocks.RichTextBlock()))))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='zipcode',
            field=models.TextField(blank=True, default='20005', null=True),
        ),
    ]
