# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 22:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20180718_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='sessions',
            field=wagtail.core.fields.StreamField([('days', wagtail.core.blocks.StructBlock([('collapsible', wagtail.core.blocks.BooleanBlock(default=True, help_text='Allow schedule sessions to expand and collapse', required=False)), ('day', wagtail.core.blocks.ChoiceBlock(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], help_text='What day of the conference is this session on?', required=False)), ('start_time', wagtail.core.blocks.TimeBlock(required=False)), ('end_time', wagtail.core.blocks.TimeBlock(required=False)), ('sessions', wagtail.core.blocks.StreamBlock([('session', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('start_time', wagtail.core.blocks.TimeBlock(required=False)), ('end_time', wagtail.core.blocks.TimeBlock(required=False)), ('speakers', wagtail.core.blocks.StreamBlock([('speaker', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(required=False)), ('twitter', wagtail.core.blocks.URLBlock(required=False)), ('title', wagtail.core.blocks.TextBlock(required=False))]))], required=False)), ('archived_video_link', wagtail.core.blocks.URLBlock(help_text='Enter youtube link after conference', required=False))]))]))], help_text='for multi-day events'))], blank=True, null=True),
        ),
    ]
