# Generated by Django 3.2.18 on 2023-04-21 21:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_auto_20190110_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='directions',
            field=wagtail.fields.StreamField([('direction', wagtail.blocks.StructBlock([('transportation_type', wagtail.blocks.CharBlock(help_text='e.g car, metro, taxi')), ('directions', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='partners',
            field=wagtail.fields.StreamField([('partner', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock()), ('type', wagtail.blocks.ChoiceBlock(choices=[('no_type', 'None'), ('premier_sponsor', 'Premier Sponsor'), ('sponsor', 'Sponsor'), ('media_partner', 'Media Partner'), ('recognized_partner', 'Recognized Partner')])), ('logo', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sessions',
            field=wagtail.fields.StreamField([('days', wagtail.blocks.StructBlock([('collapsible', wagtail.blocks.BooleanBlock(default=True, help_text='Allow schedule sessions to expand and collapse', required=False)), ('day', wagtail.blocks.ChoiceBlock(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], help_text='What day of the conference is this session on?', required=False)), ('start_time', wagtail.blocks.TimeBlock(required=False)), ('end_time', wagtail.blocks.TimeBlock(required=False)), ('sessions', wagtail.blocks.StreamBlock([('session', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('start_time', wagtail.blocks.TimeBlock(required=False)), ('end_time', wagtail.blocks.TimeBlock(required=False)), ('speakers', wagtail.blocks.StreamBlock([('speaker', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=False)), ('twitter', wagtail.blocks.URLBlock(required=False)), ('title', wagtail.blocks.TextBlock(required=False))]))], required=False)), ('archived_video_link', wagtail.blocks.URLBlock(help_text='Enter youtube link after conference', required=False))]))]))], help_text='for multi-day events'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='speakers',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('person', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=True)), ('title', wagtail.blocks.TextBlock(help_text='125 character limit', max_length=125, required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False)), ('twitter', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='venue',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('columns', wagtail.blocks.StructBlock([('left_column', wagtail.blocks.RichTextBlock()), ('right_column', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
