# Generated by Django 3.2.18 on 2023-05-19 20:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_add_alt_text_to_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='partners',
            field=wagtail.fields.StreamField([('partner', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock()), ('type', wagtail.blocks.ChoiceBlock(choices=[('no_type', 'None'), ('premier_sponsor', 'Premier Sponsor'), ('sponsor', 'Sponsor'), ('media_partner', 'Media Partner'), ('recognized_partner', 'Recognized Partner')])), ('logo', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False)), ('logo_alt_text', wagtail.blocks.CharBlock(help_text='A concise description of the image for users of assistive technology.', required=False, verbose_name='Logo alternative text'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='speakers',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('person', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=True)), ('title', wagtail.blocks.TextBlock(help_text='125 character limit', max_length=125, required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False)), ('image_alt_text', wagtail.blocks.CharBlock(help_text='A concise description of the image for users of assistive technology.', required=False, verbose_name='Image alternative text')), ('twitter', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
