# Generated by Django 3.2.18 on 2024-07-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_accordion_blocks'),
        ('conference', '0017_add_alt_text_to_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='alternate_title_image',
            field=models.ForeignKey(blank=True, help_text='This will replace the title in the introduction / cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AddField(
            model_name='conference',
            name='alternate_title_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Alternate title image alternative text'),
        ),
    ]
