# Generated by Django 3.2.18 on 2025-06-11 15:03

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_conference_social_sharing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='callout_box',
            field=wagtail.fields.RichTextField(blank=True, help_text='This will be displayed under the Description text. Leave blank for nothing to show up', null=True),
        ),
    ]
