# Generated by Django 3.2.18 on 2025-06-11 15:21

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0020_conference_callout_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='partner_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='This will be displayed under the Partner and Sponsor Logos. Leave blank for nothing to show up', null=True),
        ),
    ]
