# Generated by Django 3.2.18 on 2025-09-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0021_conference_partner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='schedule_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='speakers_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
