# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('wagtailcore', '0028_merge'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
                ('source', models.TextField(blank=True, max_length=8000, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article and Op-Ed',
            },
            bases=('home.post',),
        ),
        migrations.CreateModel(
            name='ProgramArticlesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Articles and Op-Eds Homepage for Program and Subprograms',
            },
            bases=('wagtailcore.page',),
        ),
    ]
