# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_programarticlespage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allarticleshomepage',
            options={'verbose_name': 'Homepage for all Articles and Op-Eds'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article and Op-Ed'},
        ),
        migrations.AlterModelOptions(
            name='programarticlespage',
            options={'verbose_name': 'Articles and Op-Eds Homepage for Program'},
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
