# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_programarticlespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
