# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('article', '0003_auto_20160325_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubprogramArticlesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Articles and Op-Eds Homepage for Subprogram',
            },
            bases=('wagtailcore.page',),
        ),
    ]
