# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160325_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programarticlespage',
            options={'verbose_name': 'Articles and Op-Eds Homepage for Program and Subprograms'},
        ),
    ]
