# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-03 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160628_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article/Op-Ed'},
        ),
    ]
