# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-02 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180203_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allarticleshomepage',
            options={'verbose_name': 'Articles/Op-Eds Homepage'},
        ),
    ]
