# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-25 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180402_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programarticlespage',
            options={'verbose_name': 'Articles/Op-Eds Homepage'},
        ),
    ]
