# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160328_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programblogpostspage',
            options={'verbose_name': 'Blog Homepage for Program and Subprograms'},
        ),
    ]
