# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-27 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161117_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allblogpostshomepage',
            options={'verbose_name': 'New America Blog'},
        ),
        migrations.AlterModelOptions(
            name='programblogpostspage',
            options={'verbose_name': 'Blog Posts Homepage'},
        ),
    ]
