# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='attachment',
            field=wagtail.core.fields.StreamField((('attachment', wagtail.documents.blocks.DocumentChooserBlock(required=False)),), null=True),
        ),
    ]
