# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('blog', '0004_auto_20160404_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='programblogpostspage',
            name='story_excerpt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='programblogpostspage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
