# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160422_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programblogpostspage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
