# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180718_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='attachment',
            field=wagtail.wagtailcore.fields.StreamField((('attachment', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)),), blank=True, null=True),
        ),
    ]
