# Generated by Django 3.2.18 on 2023-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='programblogpostspage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
    ]
