# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_programeventspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rsvp_link',
            field=models.URLField(blank=True),
        ),
    ]
