# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160622_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event'},
        ),
    ]
