# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20170320_0143'),
        ('event', '0004_auto_20161117_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conference.Conference'),
        ),
    ]
