# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('event', '0004_auto_20161117_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
