# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20160330_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programeventspage',
            options={'verbose_name': 'Events Homepage for Program and Subprograms'},
        ),
    ]
