# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-05 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20160404_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='soundcloud_url',
            field=models.URLField(default=b'http://www.'),
        ),
    ]
