# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.TextField(default='Washington'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_organization',
            field=models.TextField(blank=True, default='New America', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.TextField(default='D.C.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='street_address',
            field=models.TextField(default='740 15th St NW #900'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zipcode',
            field=models.TextField(default='20005'),
        ),
    ]
