# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_soundcloud_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='soundcloud_url',
            field=models.URLField(blank=True, default=b'http://www.', null=True),
        ),
    ]
