# Generated by Django 3.2.18 on 2025-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20200303_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.TextField(blank=True, default='DC'),
        ),
    ]
