# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 01:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='soundcloud',
            field=wagtail.wagtailcore.fields.StreamField((('soundcloud_embed', wagtail.wagtailembeds.blocks.EmbedBlock()),)),
        ),
    ]
