# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20160210_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpodcastspage',
            options={'verbose_name': 'Podcast Homepage for Program and Subprograms'},
        ),
    ]
