# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20160404_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='itunes_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
