# Generated by Django 3.2.18 on 2025-10-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20251009_1505'),
        ('podcast', '0006_alter_podcast_soundcloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='publication_cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='publication_cover_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Publication cover image alternative text'),
        ),
    ]
