# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0002_auto_20160428_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuotedHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Homepage for all In The News Pieces',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramQuotedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'In the News Homepage for Programs and Subprogram',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Quoted',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
                ('source', models.TextField(blank=True, max_length=8000, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'In The News Piece',
            },
            bases=('home.post',),
        ),
    ]
