# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-27 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allquotedhomepage',
            options={'verbose_name': 'In The News Homepage'},
        ),
        migrations.AlterModelOptions(
            name='programquotedpage',
            options={'verbose_name': 'In the News Homepage'},
        ),
    ]
