# Generated by Django 3.2.18 on 2025-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0002_auto_20180327_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoted',
            name='no_index_page',
            field=models.BooleanField(default=False),
        ),
    ]
