# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0003_auto_20160112_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allquotedhomepage',
            options={'verbose_name': 'Homepage for all In The News Pieces'},
        ),
        migrations.AlterModelOptions(
            name='programquotedpage',
            options={'verbose_name': 'In the News Homepage for Programs'},
        ),
        migrations.AlterModelOptions(
            name='quoted',
            options={'verbose_name': 'In The News Piece'},
        ),
        migrations.AlterField(
            model_name='quoted',
            name='source',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='quoted',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
