# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0004_auto_20160325_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programquotedpage',
            options={'verbose_name': 'In the News Homepage for Programs and Subprogram'},
        ),
    ]
