# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0005_auto_20160404_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoted',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
