# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('programs', '0001_initial'),
        ('home', '0002_auto_20160428_1942'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsubprogramrelationship',
            name='subprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programs.Subprogram'),
        ),
        migrations.AddField(
            model_name='personprogramrelationship',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='person.Person'),
        ),
        migrations.AddField(
            model_name='personprogramrelationship',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='person',
            name='belongs_to_these_programs',
            field=models.ManyToManyField(blank=True, through='person.PersonProgramRelationship', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='person',
            name='belongs_to_these_subprograms',
            field=models.ManyToManyField(blank=True, through='person.PersonSubprogramRelationship', to='programs.Subprogram'),
        ),
        migrations.AddField(
            model_name='person',
            name='feature_work_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='person',
            name='feature_work_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='person',
            name='feature_work_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='ourpeoplepage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='expertpage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
