# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20170712_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sort_priority',
            field=models.CharField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4')], help_text=b'This will override alphabetical ordering.', max_length=50, null=True),
        ),
    ]
