# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-09 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170728_1418'),
        ('person', '0005_auto_20170728_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardandleadershippeoplepage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='programpeoplepage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
