# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180201_1451'),
        ('issue', '0002_auto_20170728_1418'),
        ('person', '0005_person_sort_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTopicRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='person.Person')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issue.IssueOrTopic')),
            ],
        ),
        migrations.AddField(
            model_name='boardandleadershippeoplepage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='programpeoplepage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='person',
            name='expertise',
            field=models.ManyToManyField(blank=True, through='person.PersonTopicRelationship', to='issue.IssueOrTopic'),
        ),
    ]
