# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20180201_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fellowship_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
