# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20160115_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='belongs_to_program',
            field=models.ForeignKey(blank=True, help_text='The Program this person works for', null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=wagtail.wagtailcore.fields.StreamField((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')),)),
        ),
        migrations.AlterField(
            model_name='person',
            name='position_at_new_america',
            field=models.CharField(help_text='Position or Title at New America', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Board Member', 'Board Member'), ('Staff', 'Staff'), ('New America Fellow', 'New America Fellow'), ('Program Fellow', 'Program Fellow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_media',
            field=wagtail.wagtailcore.fields.StreamField((('twitter', wagtail.wagtailcore.blocks.URLBlock(help_text='Twitter Handle', icon='user', required=False)), ('facebook', wagtail.wagtailcore.blocks.URLBlock(help_text='Facebook Profile', icon='user', required=False)), ('youtube', wagtail.wagtailcore.blocks.URLBlock(help_text='YouTube Channel', icon='media', required=False)), ('google_plus', wagtail.wagtailcore.blocks.URLBlock(help_text='Google+ Profile', icon='user', required=False)), ('linkedin', wagtail.wagtailcore.blocks.URLBlock(help_text='LinkedIn Profile', icon='user', required=False)), ('tumblr', wagtail.wagtailcore.blocks.URLBlock(help_text='Tumblr', icon='user', required=False)))),
        ),
    ]
