# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20160210_0144'),
        ('person', '0007_auto_20160210_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProgramRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='belongs_to_program',
        ),
        migrations.AddField(
            model_name='personprogramrelationship',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='person.Person'),
        ),
        migrations.AddField(
            model_name='personprogramrelationship',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='person',
            name='belongs_to_these_programs',
            field=models.ManyToManyField(blank=True, through='person.PersonProgramRelationship', to='programs.Program'),
        ),
    ]
