# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-27 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_person_fellowship_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardandleadershippeoplepage',
            options={'verbose_name': 'Our Staff and Leadership Page'},
        ),
        migrations.AlterModelOptions(
            name='ourpeoplepage',
            options={'verbose_name': 'Our People Page'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name',), 'verbose_name': 'Person'},
        ),
        migrations.AlterModelOptions(
            name='programpeoplepage',
            options={'verbose_name': 'Our People Page'},
        ),
        migrations.AlterField(
            model_name='person',
            name='fellowship_year',
            field=models.IntegerField(blank=True, choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999)], null=True),
        ),
    ]
