# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20180327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardandleadershippeoplepage',
            name='role_query',
            field=models.CharField(choices=[('Board Member', 'Board Members'), ('Leadership Team', 'Leadership Team'), ('Central Staff', 'Central Staff')], default='Board Members', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='former',
            field=models.BooleanField(default=False, help_text='Select if person no longer serves above role.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position_at_new_america',
            field=models.CharField(blank=True, help_text='Position or Title at New America', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Board Chair', 'Board Chair'), ('Board Member', 'Board Member'), ('Fellow', 'Fellow'), ('Central Staff', 'Central Staff'), ('Program Staff', 'Program Staff'), ('External Author/Former Staff', 'External Author')], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_media',
            field=wagtail.core.fields.StreamField((('twitter', wagtail.core.blocks.URLBlock(help_text='Twitter Profile Link', icon='user', required=False)), ('facebook', wagtail.core.blocks.URLBlock(help_text='Facebook Profile', icon='user', required=False)), ('youtube', wagtail.core.blocks.URLBlock(help_text='YouTube Channel', icon='media', required=False)), ('google_plus', wagtail.core.blocks.URLBlock(help_text='Google+ Profile', icon='user', required=False)), ('linkedin', wagtail.core.blocks.URLBlock(help_text='LinkedIn Profile', icon='user', required=False)), ('tumblr', wagtail.core.blocks.URLBlock(help_text='Tumblr', icon='user', required=False)))),
        ),
        migrations.AlterField(
            model_name='person',
            name='sort_priority',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], help_text='This will override alphabetical ordering.', max_length=50, null=True),
        ),
    ]
