# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20160210_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[(b'Board Member', b'Board Member'), (b'Staff', b'Staff'), (b'New America Fellow', b'New America Fellow'), (b'Program Fellow', b'Program Fellow'), (b'External Author/Former Staff', b'External Author/Former Staff')], max_length=50),
        ),
    ]
