# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20180718_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='social_media',
            field=wagtail.wagtailcore.fields.StreamField((('twitter', wagtail.wagtailcore.blocks.URLBlock(help_text='Twitter Profile Link', icon='user', required=False)), ('facebook', wagtail.wagtailcore.blocks.URLBlock(help_text='Facebook Profile', icon='user', required=False)), ('youtube', wagtail.wagtailcore.blocks.URLBlock(help_text='YouTube Channel', icon='media', required=False)), ('google_plus', wagtail.wagtailcore.blocks.URLBlock(help_text='Google+ Profile', icon='user', required=False)), ('linkedin', wagtail.wagtailcore.blocks.URLBlock(help_text='LinkedIn Profile', icon='user', required=False)), ('tumblr', wagtail.wagtailcore.blocks.URLBlock(help_text='Tumblr', icon='user', required=False))), blank=True, null=True),
        ),
    ]
