# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20180718_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprogramrelationship',
            name='fellowship_position',
            field=models.CharField(blank=True, help_text='Set program-specific fellowship information', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personprogramrelationship',
            name='fellowship_year',
            field=models.IntegerField(blank=True, choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999)], null=True),
        ),
        migrations.AddField(
            model_name='personprogramrelationship',
            name='group',
            field=models.CharField(blank=True, choices=[('Current Fellows', 'Current Fellows'), ('Former Fellows', 'Former Fellows'), ('Advisors', 'Advisors'), ('Contributing Staff', 'Contributing Staff')], help_text="Set grouping for program's our people page", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personsubprogramrelationship',
            name='fellowship_position',
            field=models.CharField(blank=True, help_text='Set subprogram-specific fellowhip information', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personsubprogramrelationship',
            name='fellowship_year',
            field=models.IntegerField(blank=True, choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999)], null=True),
        ),
        migrations.AddField(
            model_name='personsubprogramrelationship',
            name='group',
            field=models.CharField(blank=True, choices=[('Current Fellows', 'Current Fellows'), ('Former Fellows', 'Former Fellows'), ('Advisors', 'Advisors'), ('Contributing Staff', 'Contributing Staff')], help_text="Set grouping for subprogram's our people page", max_length=50, null=True),
        ),
    ]
