# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20160310_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='leadership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[(b'Board Member', b'Board Member'), (b'New America Fellow', b'New America Fellow'), (b'Program Fellow', b'Program Fellow'), (b'Central Staff', b'Central Staff'), (b'Program Staff', b'Program Staff'), (b'External Author/Former Staff', b'External Author/Former Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_media',
            field=wagtail.wagtailcore.fields.StreamField([(b'twitter', wagtail.wagtailcore.blocks.URLBlock(help_text=b'Twitter Profile Link', icon=b'user', required=False)), (b'facebook', wagtail.wagtailcore.blocks.URLBlock(help_text=b'Facebook Profile', icon=b'user', required=False)), (b'youtube', wagtail.wagtailcore.blocks.URLBlock(help_text=b'YouTube Channel', icon=b'media', required=False)), (b'google_plus', wagtail.wagtailcore.blocks.URLBlock(help_text=b'Google+ Profile', icon=b'user', required=False)), (b'linkedin', wagtail.wagtailcore.blocks.URLBlock(help_text=b'LinkedIn Profile', icon=b'user', required=False)), (b'tumblr', wagtail.wagtailcore.blocks.URLBlock(help_text=b'Tumblr', icon=b'user', required=False))]),
        ),
    ]
