# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('programs', '0008_auto_20160311_1609'),
        ('person', '0012_auto_20160323_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSubprogramRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='feature_work_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='person',
            name='feature_work_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='person',
            name='feature_work_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='person',
            name='long_bio',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_bio',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personsubprogramrelationship',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprograms', to='person.Person'),
        ),
        migrations.AddField(
            model_name='personsubprogramrelationship',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programs.Subprogram'),
        ),
        migrations.AddField(
            model_name='person',
            name='belongs_to_these_subprograms',
            field=models.ManyToManyField(blank=True, through='person.PersonSubprogramRelationship', to='programs.Subprogram'),
        ),
    ]
