# Generated by Django 3.2.5 on 2021-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_auto_20210115_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fellowship_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personprogramrelationship',
            name='fellowship_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personsubprogramrelationship',
            name='fellowship_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
