# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_auto_20160328_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpeoplepage',
            options={'verbose_name': 'Our People Page for Programs and Subprograms'},
        ),
    ]
