# Generated by Django 3.2.18 on 2023-04-21 21:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_remove_fellowship_year_choices_on_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='social_media',
            field=wagtail.fields.StreamField([('twitter', wagtail.blocks.URLBlock(help_text='Twitter Profile Link', icon='user', required=False)), ('facebook', wagtail.blocks.URLBlock(help_text='Facebook Profile', icon='user', required=False)), ('youtube', wagtail.blocks.URLBlock(help_text='YouTube Channel', icon='media', required=False)), ('google_plus', wagtail.blocks.URLBlock(help_text='Google+ Profile', icon='user', required=False)), ('linkedin', wagtail.blocks.URLBlock(help_text='LinkedIn Profile', icon='user', required=False)), ('tumblr', wagtail.blocks.URLBlock(help_text='Tumblr', icon='user', required=False))], blank=True, null=True, use_json_field=True),
        ),
    ]
