# Generated by Django 3.2.18 on 2023-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_alter_person_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardandleadershippeoplepage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='expertpage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='ourpeoplepage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Profile image alternative text'),
        ),
        migrations.AddField(
            model_name='programpeoplepage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
    ]
