# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_auto_20160404_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
    ]
