# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_auto_20160414_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterField(
            model_name='person',
            name='belongs_to_these_subprograms',
            field=models.ManyToManyField(blank=True, through='person.PersonSubprogramRelationship', to='programs.Subprogram'),
        ),
    ]
