# Generated by Django 3.2.18 on 2023-07-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_remove_person_sort_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprogramrelationship',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, help_text='Used for ordering this person on the Program page. People with a lower sort order will appear first.', null=True),
        ),
        migrations.AddField(
            model_name='personsubprogramrelationship',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, help_text='Used for ordering this person on the Program page. People with a lower sort order will appear first.', null=True),
        ),
    ]
