# Generated by Django 3.2.18 on 2023-08-04 21:31

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0020_add_alt_text_to_images"),
        ("person", "0023_auto_20230804_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personprogramrelationship",
            name="program",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="programs.program",
            ),
        ),
        migrations.AlterField(
            model_name="personsubprogramrelationship",
            name="subprogram",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="programs.subprogram",
            ),
        ),
    ]
