# Generated by Django 3.2.18 on 2023-09-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_auto_20230811_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='fellowship_year',
        ),
        migrations.RemoveField(
            model_name='personprogramrelationship',
            name='fellowship_year',
        ),
        migrations.RemoveField(
            model_name='personsubprogramrelationship',
            name='fellowship_year',
        ),
    ]
