# Generated by Django 3.2.18 on 2024-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_auto_20240510_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprogramrelationship',
            name='group',
            field=models.CharField(blank=True, choices=[('Fellows', 'Fellows'), ('Former Fellows', 'Former Fellows'), ('Advisors', 'Advisors'), ('Contributing Staff', 'Contributing Staff'), ('Arizona State University Fellows', 'Arizona State University Fellows'), ('Former Arizona State University Fellows', 'Former Arizona State University Fellows'), ('Digital Futures Task Force', 'Digital Futures Task Force'), ('CivicAI Advisory Trust', 'CivicAI Advisory Trust'), ('Principals', 'Principals')], help_text="Set grouping for program's our people page", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personsubprogramrelationship',
            name='group',
            field=models.CharField(blank=True, choices=[('Fellows', 'Fellows'), ('Former Fellows', 'Former Fellows'), ('Advisors', 'Advisors'), ('Contributing Staff', 'Contributing Staff'), ('Arizona State University Fellows', 'Arizona State University Fellows'), ('Former Arizona State University Fellows', 'Former Arizona State University Fellows'), ('Digital Futures Task Force', 'Digital Futures Task Force'), ('CivicAI Advisory Trust', 'CivicAI Advisory Trust'), ('Principals', 'Principals')], help_text="Set grouping for subprogram's our people page", max_length=50, null=True),
        ),
    ]
