# Generated by Django 3.2.18 on 2024-07-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_alter_person_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprogramrelationship',
            name='group',
            field=models.CharField(blank=True, choices=[('Fellows', 'Fellows'), ('Former Fellows', 'Former Fellows'), ('Advisors', 'Advisors'), ('Contributing Staff', 'Contributing Staff'), ('Arizona State University Fellows', 'Arizona State University Fellows'), ('Former Arizona State University Fellows', 'Former Arizona State University Fellows'), ('Digital Futures Task Force', 'Digital Futures Task Force'), ('CivicAI Advisory Trust', 'CivicAI Advisory Trust'), ('Principals', 'Principals'), ('Digital Impact and Governance Initiative', 'Digital Impact and Governance Initiative'), ('Open Technology Institute', 'Open Technology Institute'), ('Planetary Politics', 'Planetary Politics'), ('Public Interest Technology', 'Public Interest Technology'), ('Wireless Future Project', 'Wireless Future Project')], help_text="Set grouping for program's our people page", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personsubprogramrelationship',
            name='group',
            field=models.CharField(blank=True, choices=[('Fellows', 'Fellows'), ('Former Fellows', 'Former Fellows'), ('Advisors', 'Advisors'), ('Contributing Staff', 'Contributing Staff'), ('Arizona State University Fellows', 'Arizona State University Fellows'), ('Former Arizona State University Fellows', 'Former Arizona State University Fellows'), ('Digital Futures Task Force', 'Digital Futures Task Force'), ('CivicAI Advisory Trust', 'CivicAI Advisory Trust'), ('Principals', 'Principals'), ('Digital Impact and Governance Initiative', 'Digital Impact and Governance Initiative'), ('Open Technology Institute', 'Open Technology Institute'), ('Planetary Politics', 'Planetary Politics'), ('Public Interest Technology', 'Public Interest Technology'), ('Wireless Future Project', 'Wireless Future Project')], help_text="Set grouping for subprogram's our people page", max_length=50, null=True),
        ),
    ]
