# Generated by Django 3.2.18 on 2025-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0031_auto_20240710_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='no_index_page',
            field=models.BooleanField(default=False),
        ),
    ]
