# Generated by Django 3.2.18 on 2025-06-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_alter_person_no_index_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='no_index_page',
            field=models.BooleanField(default=False),
        ),
    ]
