# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160106_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead_story',
            field=models.NullBooleanField(verbose_name='The lead story which is featured most promintently on the NA homepage or Program homepage'),
        ),
    ]
