# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 14:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160205_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media')), ('map', wagtail.wagtailcore.blocks.StructBlock([(b'data_file', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), (b'doc_uploaded', wagtail.wagtailcore.blocks.BooleanBlock(required=True)), (b'variable_option', wagtail.wagtailcore.blocks.CharBlock(max_length=500, required=True))], icon='cogs'))]),
        ),
    ]
