# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160205_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='recent_carousel',
            field=wagtail.wagtailcore.fields.StreamField((('event', wagtail.wagtailcore.blocks.PageChooserBlock()), ('policy_paper', wagtail.wagtailcore.blocks.PageChooserBlock())), blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='story_excerpt',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
