# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_lead_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='story_image',
            field=wagtail.wagtailcore.fields.StreamField([('story_image', wagtail.wagtailimages.blocks.ImageChooserBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lead_story',
            field=models.NullBooleanField(help_text='Lead story featured most promintently on the homepage or Program page'),
        ),
    ]
