# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160614_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='recent_carousel',
        ),
    ]
