# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 21:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160614_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepage',
            name='event_subscriptions',
            field=wagtail.wagtailcore.fields.StreamField([('subscription', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.CharBlock(max_length=120, required=False)), ('id', wagtail.wagtailcore.blocks.CharBlock(help_text='Enter the unique campaign monitor ID', max_length=6, required=True)), ('checked_by_default', wagtail.wagtailcore.blocks.BooleanBlock(default=False, help_text='Controls whether subscription is checked by default on the Subscribe Page', required=False))], icon='placeholder'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribepage',
            name='newsletter_subscriptions',
            field=wagtail.wagtailcore.fields.StreamField([('subscription', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.CharBlock(max_length=120, required=False)), ('id', wagtail.wagtailcore.blocks.CharBlock(help_text='Enter the unique campaign monitor ID', max_length=6, required=True)), ('checked_by_default', wagtail.wagtailcore.blocks.BooleanBlock(default=False, help_text='Controls whether subscription is checked by default on the Subscribe Page', required=False))], icon='placeholder'))], blank=True, null=True),
        ),
    ]
