# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160308_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.TextField(default='No Heading Provided'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
