# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160321_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
