# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160315_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='headline',
            new_name='post_headline',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sub_headline',
            new_name='post_sub_headline',
        ),
    ]
