# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 17:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160203_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story_image',
            field=wagtail.wagtailcore.fields.StreamField([('story_image', wagtail.wagtailimages.blocks.ImageChooserBlock())], blank=True, help_text='Image to accompany lead or feature story on the homepage or Program page', null=True),
        ),
    ]
