# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160315_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_headline',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_sub_headline',
            new_name='sub_headline',
        ),
    ]
