# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160325_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsimplepage',
            name='story_excerpt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='programsimplepage',
            name='story_excerpt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
