# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160203_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_story_1',
            field=models.NullBooleanField(help_text='First of four possible stories to feature next promintently after lead story on the homepage or Program page'),
        ),
    ]
