# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_feature_story_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_story_1',
            field=models.NullBooleanField(default=False, help_text='First of four possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lead_story',
            field=models.NullBooleanField(help_text='Lead story featured most prominently on the homepage or Program page'),
        ),
    ]
