# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20161020_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story_excerpt',
            field=models.CharField(blank=True, help_text="140 character limit. If not 'Search Description' is defined, this populates the post summary that shows up on search results on newamerica.org and is indexed by google", max_length=140, null=True),
        ),
    ]
