# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_jobspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribePage',
            fields=[
                ('orgsimplepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.OrgSimplePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.orgsimplepage',),
        ),
    ]
