# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 17:05
from __future__ import unicode_literals

from django.db import migrations
from wagtail.wagtailimages.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170117_1045'),
    ]
    forward, reverse = get_fill_filter_spec_migrations('home', 'CustomRendition')
    operations = [
        migrations.RunPython(forward, reverse),
    ]
