# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160203_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_story_2',
            field=models.NullBooleanField(help_text='Second of four possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
        migrations.AddField(
            model_name='post',
            name='feature_story_3',
            field=models.NullBooleanField(help_text='Third of four possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
        migrations.AddField(
            model_name='post',
            name='feature_story_4',
            field=models.NullBooleanField(help_text='Fourth of four possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_story_1',
            field=models.NullBooleanField(help_text='First of four possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
    ]
