# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 17:33
from __future__ import unicode_literals

from django.db import migrations
from wagtail.wagtailimages.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170118_1232'),
    ]

    forward, reverse = get_fill_filter_spec_migrations('home', 'CustomRendition')
    operations = [
        migrations.RunPython(forward, reverse),
    ]
