# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 17:33
from __future__ import unicode_literals

from django.db import migrations
# from wagtail.images.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170118_1232'),
    ]

    # forward, reverse = get_fill_filter_spec_migrations('home', 'CustomRendition')
    operations = [
        # Commented out in Wagtail 2.4 upgrade as the wagtailimages.Filter model has been removed
        # and this migration has already been run
        # migrations.RunPython(forward, reverse),
    ]
