# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160203_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feature_story_4',
        ),
        migrations.AddField(
            model_name='homepage',
            name='four_story_template',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='homepage',
            name='one_story_template',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='homepage',
            name='three_story_template',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='homepage',
            name='two_story_template',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_story_1',
            field=models.NullBooleanField(help_text='First of three possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_story_2',
            field=models.NullBooleanField(help_text='Second of three possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_story_3',
            field=models.NullBooleanField(help_text='Third of three possible stories to feature next prominently after lead story on the homepage or Program page'),
        ),
    ]
