# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160203_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature_story_1',
            new_name='featured_story',
        ),
        migrations.RemoveField(
            model_name='post',
            name='feature_story_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='feature_story_3',
        ),
    ]
