# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160203_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='four_story_template',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='one_story_template',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='three_story_template',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='two_story_template',
        ),
        migrations.AddField(
            model_name='homepage',
            name='template',
            field=models.CharField(blank=True, choices=[('Four Story Template', 'Four Story Template'), ('Three Story Template', 'Three Story Template'), ('Two Story Template', 'Two Story Template'), ('One Story Template', 'One Story Template')], max_length=50, null=True),
        ),
    ]
