# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20160203_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='template',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_story',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lead_story',
        ),
        migrations.AddField(
            model_name='post',
            name='home_page_status',
            field=models.IntegerField(choices=[(0, 'Regular Story'), (1, 'Lead Story'), (2, 'Feature Story')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='program_page_status',
            field=models.IntegerField(choices=[(0, 'Regular Story'), (1, 'Lead Story'), (2, 'Feature Story')], default=0),
        ),
        migrations.AddField(
            model_name='homepage',
            name='template',
            field=models.IntegerField(choices=[(4, 'Four Story Template'), (3, 'Three Story Template'), (2, 'Two Story Template'), (1, 'One Story Template')], default=3),
        ),
    ]
