# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160204_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='story_image',
        ),
    ]
