# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('home', '0018_remove_post_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
