# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20160204_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='lead_story_1',
            new_name='lead_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='lead_story_2',
            new_name='lead_2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='lead_story_3',
            new_name='lead_3',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='lead_story_4',
            new_name='lead_4',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='secondary_story_1',
            new_name='secondary_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='secondary_story_2',
            new_name='secondary_2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='secondary_story_3',
            new_name='secondary_3',
        ),
    ]
