# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20160204_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='home_page_status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='program_page_status',
        ),
        migrations.AddField(
            model_name='post',
            name='story_excerpt',
            field=models.TextField(blank=True),
        ),
    ]
