# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20160204_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='secondary_1',
            new_name='feature_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='secondary_2',
            new_name='feature_2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='secondary_3',
            new_name='feature_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='template',
        ),
    ]
