# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170616_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=999)),
                ('formatted_address', models.CharField(blank=True, max_length=999, null=True)),
                ('street_number', models.CharField(blank=True, max_length=999, null=True)),
                ('street', models.CharField(blank=True, max_length=999, null=True)),
                ('city', models.CharField(blank=True, max_length=999, null=True)),
                ('state_or_province', models.CharField(blank=True, max_length=999, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=999, null=True)),
                ('county', models.CharField(blank=True, max_length=999, null=True)),
                ('country', models.CharField(blank=True, max_length=999, null=True)),
                ('latitude', models.CharField(blank=True, max_length=999, null=True)),
                ('longitude', models.CharField(blank=True, max_length=999, null=True)),
                ('post', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='home.Post')),
            ],
        ),
    ]
