# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20170725_1430'),
        ('home', '0024_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTopicRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='home.Post')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issue.IssueOrTopic')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.ManyToManyField(blank=True, through='home.PostTopicRelationship', to='issue.IssueOrTopic'),
        ),
    ]
