# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 14:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20180203_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_pages',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock())], blank=True),
        ),
    ]
