# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
        ('home', '0027_homepage_about_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHomePageRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_title', models.TextField(blank=True)),
                ('program', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='home.HomePage')),
                ('subscription_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subscribe.SubscriptionSegment')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscription_segments',
            field=models.ManyToManyField(blank=True, through='home.SubscriptionHomePageRelationship', to='subscribe.SubscriptionSegment'),
        ),
    ]
