# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-18 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180718_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendition',
            name='filter',
        ),
    ]
