# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20180727_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAboutHomePage',
            fields=[
                ('programsimplepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ProgramSimplePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.programsimplepage',),
        ),
        migrations.CreateModel(
            name='ProgramAboutPage',
            fields=[
                ('programsimplepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ProgramSimplePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.programsimplepage',),
        ),
    ]
