# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_programabouthomepage_programaboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='down_for_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
