# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-13 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20190926_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ordered_date_string',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
