# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-26 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20200225_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ordered_date_string',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
