# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-03 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20200226_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AlterModelOptions(
            name='programaboutpage',
            options={'verbose_name': 'Program About Page'},
        ),
    ]
