# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-07 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20200302_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirectpage',
            options={'verbose_name': 'External Website'},
        ),
    ]
