# Generated by Django 3.0.3 on 2020-08-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20200307_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postauthorrelationship',
            options={'ordering': ['pk']},
        ),
    ]
