# Generated by Django 3.0.11 on 2021-04-23 16:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0055_auto_20210208_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_with_brief_permission', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Group that has permission to perform the "Publish" action on Brief pages. Only superusers and users that are members of the group selected here may do so, otherwise reports must go through the applicable workflow.', related_name='_publicationpermissions_groups_with_brief_permission_+', to='auth.Group')),
                ('groups_with_report_permission', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Group that has permission to perform the "Publish" action on Report pages. Only superusers and users that are members of the group selected here may do so, otherwise reports must go through the applicable workflow.', related_name='_publicationpermissions_groups_with_report_permission_+', to='auth.Group')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
