# Generated by Django 3.0.7 on 2020-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20201218_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(help_text='Date that the Survey was collected.', verbose_name='Post date'),
        ),
    ]
