# Generated by Django 3.0.11 on 2021-05-19 15:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_publicationpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribepage',
            name='event_subscriptions',
            field=wagtail.fields.StreamField([('subscription', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(max_length=120, required=False)), ('id', wagtail.blocks.CharBlock(help_text='Enter the unique campaign monitor ID', max_length=6, required=True))], icon='placeholder'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribepage',
            name='newsletter_subscriptions',
            field=wagtail.fields.StreamField([('subscription', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.CharBlock(max_length=120, required=False)), ('id', wagtail.blocks.CharBlock(help_text='Enter the unique campaign monitor ID', max_length=6, required=True))], icon='placeholder'))], blank=True, null=True),
        ),
    ]
