# Generated by Django 3.2.18 on 2023-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20230421_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsimplepage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='post',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='programsimplepage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='redirectpage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
    ]
