# Generated by Django 4.2.9 on 2024-01-12 21:05

import modelcluster.fields
import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("home", "0064_auto_20231208_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="publicationpermissions",
            name="groups_with_brief_permission",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text='Group that has permission to perform the "Publish" action on Brief pages. Only superusers and users that are members of the group selected here may do so, otherwise reports must go through the applicable workflow.',
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="publicationpermissions",
            name="groups_with_report_permission",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text='Group that has permission to perform the "Publish" action on Report pages. Only superusers and users that are members of the group selected here may do so, otherwise reports must go through the applicable workflow.',
                related_name="+",
                to="auth.group",
            ),
        ),
    ]
