# Generated by Django 3.2.18 on 2024-10-15 17:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_accordion_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lead_stories',
            field=wagtail.fields.StreamField([('internal', wagtail.blocks.PageChooserBlock()), ('external', wagtail.blocks.StructBlock([('link', wagtail.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_alt', wagtail.blocks.CharBlock(required=False)), ('heading', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock(required=False)), ('tag', wagtail.blocks.CharBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
