# Generated by Django 3.2.18 on 2024-10-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_homepage_lead_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='lead_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='lead_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='lead_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='lead_4',
        ),
    ]
