# Generated by Django 3.2.18 on 2025-06-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0070_projectrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Project Form Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
