# Generated by Django 3.2.18 on 2025-06-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_projectformpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequests',
            name='body',
        ),
        migrations.RemoveField(
            model_name='projectrequests',
            name='custom_interface',
        ),
        migrations.RemoveField(
            model_name='projectrequests',
            name='data_project_external_script',
        ),
        migrations.RemoveField(
            model_name='projectrequests',
            name='story_excerpt',
        ),
        migrations.RemoveField(
            model_name='projectrequests',
            name='story_image',
        ),
        migrations.RemoveField(
            model_name='projectrequests',
            name='story_image_alt',
        ),
    ]
