# Generated by Django 3.2.18 on 2025-06-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20250625_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectformpage',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
