# Generated by Django 3.2.18 on 2025-06-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_projectformpage_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectformpage',
            name='svg_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
