# Generated by Django 3.2.18 on 2025-06-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_projectformpage_svg_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequests',
            name='intro_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
