# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_programbookspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book'},
        ),
    ]
