# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_publication_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programbookspage',
            options={'verbose_name': 'Books Homepage for Program and Subprogram'},
        ),
    ]
