# Generated by Django 3.2.18 on 2023-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180327_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_cover_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Publication cover image alternative text'),
        ),
    ]
