# Generated by Django 3.2.18 on 2025-05-14 19:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20250512_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='media_links',
            field=wagtail.fields.StreamField([('featured', wagtail.blocks.StructBlock([('label', wagtail.blocks.TextBlock(max_length=30, required=False)), ('description', wagtail.blocks.TextBlock(max_length=65, required=False)), ('url', wagtail.blocks.URLBlock(default='https://www.', required=True))], null=True, required=False))], blank=True, max_length=4, null=True, use_json_field=True),
        ),
    ]
