# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPolicyPapersHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Homepage for all Policy Papers',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PolicyPaper',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
                ('paper_url', wagtail.core.fields.StreamField([(b'policy_paper_url', wagtail.core.blocks.URLBlock(null=True, required=False))])),
                ('attachment', wagtail.core.fields.StreamField([(b'attachment', wagtail.documents.blocks.DocumentChooserBlock(null=True, required=False))])),
                ('publication_cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.post',),
        ),
        migrations.CreateModel(
            name='ProgramPolicyPapersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Policy Paper Homepage for Programs and Subprograms',
            },
            bases=('wagtailcore.page',),
        ),
    ]
