# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-27 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_paper', '0002_auto_20161117_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpolicypaperspage',
            options={'verbose_name': 'Policy Papers Homepage'},
        ),
    ]
