# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 01:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('policy_paper', '0003_policypaper_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypaper',
            name='attachment',
            field=wagtail.wagtailcore.fields.StreamField((('attachment', wagtail.wagtaildocs.blocks.DocumentChooserBlock(null=True, required=False)),)),
        ),
        migrations.AlterField(
            model_name='policypaper',
            name='paper_url',
            field=wagtail.wagtailcore.fields.StreamField((('policy_paper_url', wagtail.wagtailcore.blocks.URLBlock(null=True, required=False)),)),
        ),
    ]
