# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('policy_paper', '0004_auto_20180718_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypaper',
            name='attachment',
            field=wagtail.core.fields.StreamField((('attachment', wagtail.documents.blocks.DocumentChooserBlock(null=True, required=False)),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policypaper',
            name='paper_url',
            field=wagtail.core.fields.StreamField((('policy_paper_url', wagtail.core.blocks.URLBlock(null=True, required=False)),), blank=True, null=True),
        ),
    ]
