# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('policy_paper', '0004_auto_20160210_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policypaper',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='policypaper',
            name='publication_cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
