# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_paper', '0005_auto_20160328_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpolicypaperspage',
            options={'verbose_name': 'Policy Paper Homepage for Programs and Subprograms'},
        ),
    ]
