# Generated by Django 3.2.18 on 2023-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_paper', '0006_auto_20230421_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypaper',
            name='publication_cover_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Publication cover image alternative text'),
        ),
    ]
