# Generated by Django 3.2.18 on 2023-06-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_add_alt_text_to_blocks'),
        ('the_thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='featured_page_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.post'),
        ),
        migrations.AddField(
            model_name='thread',
            name='featured_page_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.post'),
        ),
        migrations.AddField(
            model_name='thread',
            name='featured_page_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.post'),
        ),
    ]
