# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProgramRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_title', models.TextField(blank=True)),
                ('program', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.Program')),
                ('subscription_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subscribe.SubscriptionSegment')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionSubprogramRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_name', models.TextField(blank=True)),
                ('subprogram', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprograms', to='programs.Subprogram')),
                ('subscription_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subscribe.SubscriptionSegment')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='subscription_segments',
            field=models.ManyToManyField(blank=True, through='programs.SubscriptionProgramRelationship', to='subscribe.SubscriptionSegment'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='subscription_segments',
            field=models.ManyToManyField(blank=True, through='programs.SubscriptionSubprogramRelationship', to='subscribe.SubscriptionSegment'),
        ),
    ]
