# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-21 13:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20170719_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprogramrelationship',
            name='program',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='subscriptionsubprogramrelationship',
            name='subprogram',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='programs.Subprogram'),
        ),
    ]
