# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20160106_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.NullBooleanField(help_text=b'Check box if this is a location based program i.e. New America NYC'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='location',
            field=models.NullBooleanField(help_text=b'Check box if this is a location based program i.e. New America NYC'),
        ),
    ]
