# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('programs', '0003_auto_20170721_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Homepage for all program publications',
            },
            bases=('wagtailcore.page',),
        ),
    ]
