# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20160127_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')))),
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.NullBooleanField(help_text='Check box if this is a location based program i.e. New America NYC'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Name of Program', max_length=100),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='description',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')))),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='location',
            field=models.NullBooleanField(help_text='Check box if this is a location based program i.e. New America NYC'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='name',
            field=models.CharField(help_text='Name of Program', max_length=100),
        ),
    ]
