# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-23 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_publicationspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subprogram',
            options={'ordering': ('title',), 'verbose_name': 'Subprogram Page'},
        ),
        migrations.AddField(
            model_name='subprogram',
            name='template',
            field=models.CharField(choices=[(b'programs/program.html', b'Full'), (b'simple_program.html', b'Simple')], default=b'programs/program.html', max_length=100),
        ),
    ]
