# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20180122_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='fellowship',
            field=models.NullBooleanField(help_text=b'Select if this is a fellowship program'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='fellowship',
            field=models.NullBooleanField(help_text=b'Select if this is a fellowship program'),
        ),
    ]
