# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-26 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20180205_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('title',), 'verbose_name': 'Program Homepage'},
        ),
        migrations.AlterModelOptions(
            name='subprogram',
            options={'ordering': ('title',), 'verbose_name': 'Project Homepage'},
        ),
    ]
