# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 18:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20160210_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sidebar_menu_about_us_pages',
            field=wagtail.wagtailcore.fields.StreamField([(b'Item', wagtail.wagtailcore.blocks.PageChooserBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='sidebar_menu_initiatives_and_projects_pages',
            field=wagtail.wagtailcore.fields.StreamField([(b'Item', wagtail.wagtailcore.blocks.PageChooserBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='sidebar_menu_our_work_pages',
            field=wagtail.wagtailcore.fields.StreamField([(b'Item', wagtail.wagtailcore.blocks.PageChooserBlock())], blank=True),
        ),
    ]
