# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20160307_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='description',
            field=models.TextField(),
        ),
    ]
