# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-29 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('programs', '0008_auto_20180327_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogProject',
            fields=[
                ('subprogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='programs.Subprogram')),
            ],
            options={
                'verbose_name': 'Blog',
            },
            bases=('programs.subprogram',),
        ),
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('subprogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='programs.Subprogram')),
                ('redirect_page', models.ForeignKey(blank=True, help_text=b'Select a report or other post that you would like to show up as a project in your Initiatives & Projects list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('programs.subprogram',),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='template',
            field=models.CharField(choices=[(b'programs/program.html', b'Full'), (b'simple_program.html', b'Efficiency'), (b'programs/program.html', b'Collection')], default=b'programs/program.html', max_length=100),
        ),
    ]
