# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('programs', '0008_auto_20160311_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='feature_carousel',
            field=wagtail.wagtailcore.fields.StreamField([(b'page', wagtail.wagtailcore.blocks.PageChooserBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='feature_carousel',
            field=wagtail.wagtailcore.fields.StreamField([(b'page', wagtail.wagtailcore.blocks.PageChooserBlock())], blank=True),
        ),
    ]
