# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-25 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20180329_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subprogram',
            options={'ordering': ('title',), 'verbose_name': 'Initiative Homepage'},
        ),
        migrations.AddField(
            model_name='program',
            name='hide_subscription_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='subscription_card_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='hide_subscription_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='subscription_card_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
