# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20160325_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.NullBooleanField(help_text=b'Select if location based program i.e. New America NYC'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='location',
            field=models.NullBooleanField(help_text=b'Select if location based program i.e. New America NYC'),
        ),
    ]
