# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_auto_20160418_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='subprogram',
            options={'ordering': ('title',), 'verbose_name': 'Subprogram/Initiative Page'},
        ),
    ]
