# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_programabouthomepage_programaboutpage'),
        ('programs', '0013_featuredprogrampage_featuredsubprogrampage'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredprogrampage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='featuredsubprogrampage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
