# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('programs', '0013_auto_20160422_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_logo',
            new_name='desktop_program_logo',
        ),
        migrations.AddField(
            model_name='program',
            name='mobile_program_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
