# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20181019_0632'),
        ('person', '0011_auto_20180807_1449'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('programs', '0014_auto_20180809_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogproject',
            name='subprogram_ptr',
        ),
        migrations.RemoveField(
            model_name='blogseries',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='about_us_page',
        ),
        migrations.RemoveField(
            model_name='program',
            name='feature_1',
        ),
        migrations.RemoveField(
            model_name='program',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='feature_carousel',
        ),
        migrations.RemoveField(
            model_name='program',
            name='lead_1',
        ),
        migrations.RemoveField(
            model_name='program',
            name='lead_2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='lead_3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='lead_4',
        ),
        migrations.RemoveField(
            model_name='program',
            name='sidebar_menu_initiatives_and_projects_pages',
        ),
        migrations.RemoveField(
            model_name='program',
            name='sidebar_menu_our_work_pages',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='about_us_page',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='feature_1',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='feature_carousel',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='lead_1',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='lead_2',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='lead_3',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='lead_4',
        ),
        migrations.DeleteModel(
            name='BlogProject',
        ),
        migrations.DeleteModel(
            name='BlogSeries',
        ),
    ]
