# Generated by Django 3.0.7 on 2021-01-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_auto_20181019_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',), 'verbose_name': 'Project'},
        ),
    ]
