# Generated by Django 3.0.7 on 2021-01-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_auto_20181019_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='template',
            field=models.CharField(choices=[('programs/program.html', 'Full'), ('simple_program.html', 'Efficiency'), ('programs/program.html', 'Collection'), ('survey/surveys_home_page.html', 'Survey')], default='programs/program.html', max_length=100),
        ),
    ]
