# Generated by Django 3.2.3 on 2021-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20210527_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='former',
            field=models.BooleanField(default=False, help_text='Select if no longer active'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='former',
            field=models.BooleanField(default=False, help_text='Select if no longer active'),
        ),
    ]
