# Generated by Django 3.2.18 on 2023-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_alter_program_sidebar_menu_about_us_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredprogrampage',
            name='featured_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Featured image alternative text'),
        ),
        migrations.AddField(
            model_name='featuredsubprogrampage',
            name='featured_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Featured image alternative text'),
        ),
        migrations.AddField(
            model_name='program',
            name='desktop_program_logo_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Desktop program logo alternative text'),
        ),
        migrations.AddField(
            model_name='program',
            name='mobile_program_logo_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Mobile program logo alternative text'),
        ),
        migrations.AddField(
            model_name='program',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Story image alternative text'),
        ),
    ]
