# Generated by Django 3.2.18 on 2023-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_add_alt_text_to_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionsubprogramrelationship',
            name='subprogram',
        ),
        migrations.RemoveField(
            model_name='subscriptionsubprogramrelationship',
            name='subscription_segment',
        ),
        migrations.RemoveField(
            model_name='program',
            name='subscription_segments',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='subscription_segments',
        ),
        migrations.DeleteModel(
            name='SubscriptionProgramRelationship',
        ),
        migrations.DeleteModel(
            name='SubscriptionSubprogramRelationship',
        ),
    ]
