# Generated by Django 3.2.18 on 2024-03-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_reverse_featured_subprogram_pages_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramNavOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Human-readable description for these options to show when listing in the Wagtail admin.')),
                ('url_label_array', models.TextField(help_text='Must contain an array of objects formatted as JSON text.  Example: [{"url": "about/", "label": "About Page"}, {"url": "our-people/", "label": "All Our People"}]')),
            ],
            options={
                'verbose_name_plural': 'Program Nav Options',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='nav_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.programnavoptions'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='nav_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.programnavoptions'),
        ),
    ]
