# Generated by Django 3.2.18 on 2024-04-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_program_nav_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='display_logo_as_name',
            field=models.BooleanField(default=False, verbose_name='Display program logo instead of text program name'),
        ),
    ]
