# Generated by Django 3.2.18 on 2024-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_program_display_logo_as_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredprogrampage',
            name='show_page_type',
            field=models.BooleanField(default=True, help_text='If checked, a label will be displayed on the card that shows the type of the featured page.'),
        ),
        migrations.AddField(
            model_name='featuredprogrampage',
            name='story_excerpt',
            field=models.TextField(blank=True, default='', help_text='Story excerpt for feature card. If blank, use the excerpt of the featured page.'),
        ),
        migrations.AddField(
            model_name='featuredprogrampage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title for feature card. If blank, use the title of the featured page.', max_length=500),
        ),
        migrations.AddField(
            model_name='featuredsubprogrampage',
            name='show_page_type',
            field=models.BooleanField(default=True, help_text='If checked, a label will be displayed on the card that shows the type of the featured page.'),
        ),
        migrations.AddField(
            model_name='featuredsubprogrampage',
            name='story_excerpt',
            field=models.TextField(blank=True, default='', help_text='Story excerpt for feature card. If blank, use the excerpt of the featured page.'),
        ),
        migrations.AddField(
            model_name='featuredsubprogrampage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title for feature card. If blank, use the title of the featured page.', max_length=500),
        ),
        migrations.AddField(
            model_name='program',
            name='show_about_card_label',
            field=models.BooleanField(default=True, help_text='If checked, an "About" label will be displayed on the card that shows the description text.'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='show_about_card_label',
            field=models.BooleanField(default=True, help_text='If checked, an "About" label will be displayed on the card that shows the description text.'),
        ),
    ]
