# Generated by Django 3.0.7 on 2020-12-17 20:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import multiselectfield.db.fields
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0054_auto_20200810_1541'),
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
            ],
            options={
                'verbose_name': 'Expert Commentary',
            },
            bases=('home.post', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.CreateModel(
            name='Commented_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Commentary')),
            ],
        ),
        migrations.CreateModel(
            name='DemographicKey',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': 'Demographic Keys',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramSurveysPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Surveys Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SurveyOrganization',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': 'Survey Organizations',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SurveyValuesIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Surveyindex Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
                ('year', models.IntegerField(blank=True, default=2000, help_text='Year Survey was condicted.')),
                ('month', models.IntegerField(choices=[(0, 'N/A'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=None, help_text='Month Survey was condicted, if applicable.')),
                ('sample_number', models.CharField(blank=True, max_length=250, null=True)),
                ('sample_demos', models.CharField(blank=True, help_text='Text displayed on the dashboard', max_length=250, null=True)),
                ('findings', wagtail.core.fields.RichTextField(blank=True, max_length=12500, null=True)),
                ('data_type', multiselectfield.db.fields.MultiSelectField(choices=[('QUANT', 'Quantitative'), ('QUAL', 'Qualitative')], default=['QUANT', 'QUAL'], max_length=10)),
                ('national', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('assoc_commentary', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='surveys', through='survey.Commented_Survey', to='survey.Commentary')),
                ('demos_key', modelcluster.fields.ParentalManyToManyField(blank=True, default=False, help_text='Indexable demographic groups', to='survey.DemographicKey')),
                ('org', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='SurveyOrganization', to='survey.SurveyOrganization')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.post',),
        ),
        migrations.AddField(
            model_name='commented_survey',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='assoc_surveys',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='commentaries', through='survey.Commented_Survey', to='survey.Survey'),
        ),
    ]
