# Generated by Django 3.0.7 on 2021-01-06 20:52

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey Reports'},
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='button',
            field=models.CharField(blank=True, help_text='Subscribe button text', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='cta',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Displayed on the Survey Reports page', max_length=250),
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='submissions',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='subscribe',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Displayed on bottom of the Survey Reports page', max_length=250),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(blank=True, help_text='A brief description of the survey. 500 chars max', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='month',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default=None, help_text='Month Survey was conducted, if applicable.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surveyshomepage',
            name='subheading',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
