# Generated by Django 3.0.7 on 2021-01-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey'},
        ),
        migrations.AlterModelOptions(
            name='surveyshomepage',
            options={'verbose_name': 'Survey Database'},
        ),
        migrations.AlterModelOptions(
            name='surveyvaluesindex',
            options={'verbose_name': 'Survey Filters Parent'},
        ),
    ]
