# Generated by Django 3.0.7 on 2020-12-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTags',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': 'Survey Tags',
            },
            bases=('wagtailcore.page',),
        ),
    ]
