# Generated by Django 3.0.7 on 2020-12-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='month',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=None, help_text='Month Survey was conducted, if applicable.'),
        ),
    ]
