# Generated by Django 3.0.7 on 2021-02-08 23:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0055_auto_20210208_1856'),
        ('survey', '0002_auto_20210112_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedCommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Post')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commented_survey',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='commented_survey',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='assoc_commentary',
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
        migrations.DeleteModel(
            name='Commented_Survey',
        ),
        migrations.AddField(
            model_name='associatedcommentary',
            name='survey',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_commentary', to='survey.Survey'),
        ),
    ]
