# Generated by Django 3.0.7 on 2020-12-18 19:14

from django.db import migrations, models
import modelcluster.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveytags'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, default=False, help_text='Select from available tags', to='survey.SurveyTags', verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='assoc_commentary',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='surveys', through='survey.Commented_Survey', to='survey.Commentary', verbose_name='Associated Commentary'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='data_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('QUANT', 'Quantitative'), ('QUAL', 'Qualitative')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='demos_key',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, default=False, help_text='Indexable demographic groups', to='survey.DemographicKey', verbose_name='Demographics Keys'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='file',
            field=models.FileField(blank=True, help_text='Add a file containing the survey details.', null=True, upload_to='', verbose_name='Survey File'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='link',
            field=models.URLField(blank=True, help_text='Add a link to a webpage containing the survey details.', null=True, verbose_name='Link to Survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='national',
            field=models.BooleanField(default=True, help_text='Indicates whether the survey was nationally representative or not.', verbose_name='Nationally Representative?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='org',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='SurveyOrganization', to='survey.SurveyOrganization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='sample_demos',
            field=models.CharField(blank=True, help_text='Text displayed on the dashboard', max_length=250, null=True, verbose_name='Sample Demographics'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='sample_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
