# Generated by Django 3.0.7 on 2020-12-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20201218_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='year',
            field=models.IntegerField(blank=True, default=2000, help_text='Year Survey was conducted.'),
        ),
    ]
