# Generated by Django 3.0.7 on 2021-01-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210104_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey Reports'},
        ),
    ]
