# Generated by Django 3.0.7 on 2020-12-18 21:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20201218_1414'),
        ('survey', '0003_auto_20201218_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsurveyspage',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=1500, verbose_name='About This Project'),
        ),
        migrations.AddField(
            model_name='programsurveyspage',
            name='methodology',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='programsurveyspage',
            name='partner_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='programsurveyspage',
            name='subheading',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
