# Generated by Django 3.0.7 on 2020-12-04 16:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveyhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyhomepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
