# Generated by Django 3.0.7 on 2021-01-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210104_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='month',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default=None, help_text='Month Survey was conducted, if applicable.', max_length=3),
        ),
    ]
