# Generated by Django 3.0.7 on 2020-12-21 22:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20200109_1646'),
        ('survey', '0005_auto_20201221_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name': 'Insights & Analysis'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sample_demos',
        ),
        migrations.CreateModel(
            name='SurveyAuthorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='person.Person')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='survey.SurveysHomePage')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='page_authors',
            field=models.ManyToManyField(blank=True, through='survey.SurveyAuthorRelationship', to='person.Person'),
        ),
    ]
