# Generated by Django 3.0.7 on 2020-12-07 22:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0052_pagelogentry'),
        ('survey', '0006_auto_20201207_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Demographics Keys',
            },
        ),
        migrations.CreateModel(
            name='ProgramSurveysPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Surveys Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Survey_Orgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Survey Organizations',
            },
        ),
        migrations.CreateModel(
            name='Survey_Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Survey Years',
            },
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='sample_size',
        ),
        migrations.AddField(
            model_name='survey',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.RemoveField(
            model_name='survey',
            name='demos_key',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='org',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='year',
        ),
        migrations.DeleteModel(
            name='SurveyHomepage',
        ),
        migrations.AddField(
            model_name='survey',
            name='demos_key',
            field=modelcluster.fields.ParentalManyToManyField(to='survey.Demo_Key'),
        ),
        migrations.AddField(
            model_name='survey',
            name='org',
            field=modelcluster.fields.ParentalManyToManyField(to='survey.Survey_Orgs'),
        ),
        migrations.AddField(
            model_name='survey',
            name='year',
            field=modelcluster.fields.ParentalManyToManyField(to='survey.Survey_Years'),
        ),
    ]
