# Generated by Django 3.0.7 on 2020-12-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20201221_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyshomepage',
            name='page_authors',
        ),
    ]
