# Generated by Django 3.0.7 on 2020-12-08 00:43

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20201207_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Month Survey was condicted, if applicable.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='year',
            field=modelcluster.fields.ParentalManyToManyField(help_text='Year Survey was condicted.', to='survey.Survey_Years'),
        ),
    ]
