# Generated by Django 3.0.7 on 2020-12-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20200109_1646'),
        ('survey', '0007_remove_surveyshomepage_page_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyAuthorRelationship',
            new_name='PageAuthorRelationship',
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='page_author',
            field=models.ManyToManyField(blank=True, through='survey.PageAuthorRelationship', to='person.Person'),
        ),
    ]
