# Generated by Django 3.0.7 on 2021-01-04 22:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210104_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyshomepage',
            name='submittal',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
