# Generated by Django 3.0.7 on 2020-12-21 23:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20201221_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A brief description of the survey. 500 chars max', max_length=500, null=True),
        ),
    ]
