# Generated by Django 3.0.7 on 2021-01-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_surveyshomepage_submittal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyshomepage',
            old_name='submittal',
            new_name='submissions',
        ),
    ]
