# Generated by Django 3.0.7 on 2020-12-08 17:47

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20201207_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='demos_key',
            field=modelcluster.fields.ParentalManyToManyField(help_text='Indexable demographic groups', to='survey.Demo_Key'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='sample_demos',
            field=models.CharField(blank=True, help_text='Text displayed on the dashboard', max_length=250, null=True),
        ),
    ]
