# Generated by Django 3.0.7 on 2020-12-10 19:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20200810_1541'),
        ('survey', '0009_auto_20201208_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
            ],
            options={
                'verbose_name': 'Expert Commentary',
            },
            bases=('home.post', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.AddField(
            model_name='survey',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='month',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=None, help_text='Month Survey was condicted, if applicable.'),
        ),
    ]
