# Generated by Django 3.0.7 on 2021-01-06 18:45

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20210104_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyshomepage',
            name='eratta',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='surveyshomepage',
            name='subheading',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
