# Generated by Django 3.0.7 on 2021-01-06 19:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20210106_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyshomepage',
            name='eratta',
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='cta',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Displayed on the Survey Reports page', max_length=250),
        ),
    ]
