# Generated by Django 3.0.7 on 2020-12-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20201210_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commented_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Commentary')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='commentary',
            name='assoc_surveys',
            field=models.ManyToManyField(through='survey.Commented_Survey', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='assoc_commentary',
            field=models.ManyToManyField(through='survey.Commented_Survey', to='survey.Commentary'),
        ),
    ]
