# Generated by Django 3.0.7 on 2020-12-11 05:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20201210_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='assoc_surveys',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='commentaries', through='survey.Commented_Survey', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='commented_survey',
            name='commentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Commentary'),
        ),
        migrations.AlterField(
            model_name='commented_survey',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='assoc_commentary',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='surveys', through='survey.Commented_Survey', to='survey.Commentary'),
        ),
    ]
