# Generated by Django 3.0.7 on 2021-01-06 20:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20210106_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyshomepage',
            name='button',
            field=models.CharField(blank=True, help_text='Subscribe button text', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyshomepage',
            name='subscribe',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Displayed on bottom of the Survey Reports page', max_length=250),
        ),
    ]
