# Generated by Django 3.0.7 on 2020-12-14 23:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('survey', '0012_auto_20201211_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Orgs_Index',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='survey_orgs',
            name='title',
        ),
        migrations.AlterField(
            model_name='survey',
            name='demos_key',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, default=False, help_text='Indexable demographic groups', to='survey.Demo_Key'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='org',
            field=modelcluster.fields.ParentalManyToManyField(related_name='Survey_Orgs', to='survey.Survey_Orgs'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='year',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Year Survey was condicted.', to='survey.Survey_Years'),
        ),
    ]
