# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 19:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyedition',
            name='edition_stories',
            field=wagtail.wagtailcore.fields.StreamField([('Story', wagtail.wagtailcore.blocks.PageChooserBlock())], blank=True),
        ),
    ]
