# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyarticle',
            options={'verbose_name': 'Weekly Article'},
        ),
    ]
