# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('weekly', '0002_auto_20161117_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllWeeklyArticlesHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='weekly',
            options={'verbose_name': 'Weekly Editions'},
        ),
    ]
