# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_weeklyedition_edition_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyedition',
            name='edition_stories',
        ),
    ]
