# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-25 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_auto_20180226_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allweeklyarticleshomepage',
            options={'verbose_name': 'Weekly Articles Homepage'},
        ),
    ]
