# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-13 21:26
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Value as V, F
from django.db.models.functions import Concat


def create_ordered_date(apps, schema_editor):
    Post = apps.get_model('home', 'Post')
    Post.objects.all().update(ordered_date_string=Concat(F('date'), V('-'), F('id')))


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0004_auto_20180424_2142'),
    ]

    operations = [
        migrations.RunPython(create_ordered_date, reverse_code=migrations.RunPython.noop),
    ]
