# Generated by Django 3.0.11 on 2021-04-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0005_populate_post_ordered_date_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekly',
            options={'verbose_name': 'The Weekly'},
        ),
    ]
