# Generated by Django 3.2.18 on 2025-04-16 15:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureSecurityForumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(help_text='This will be the ABOUT text')),
                ('subheading', models.TextField(blank=True, null=True)),
                ('story_excerpt', models.CharField(blank=True, max_length=140, null=True, verbose_name='excerpt')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
