# Generated by Django 3.2.18 on 2025-04-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresecurityforumpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='futuresecurityforumpage',
            name='story_excerpt',
        ),
        migrations.RemoveField(
            model_name='futuresecurityforumpage',
            name='subheading',
        ),
    ]
