# Generated by Django 3.2.18 on 2025-04-16 15:39

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0002_auto_20250416_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='description',
            field=wagtail.fields.RichTextField(default='Test', help_text='This will be the ABOUT text'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='story_excerpt',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='subheading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
