# Generated by Django 3.2.18 on 2025-04-16 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_homepage_lead_stories'),
        ('future_security_forum', '0003_auto_20250416_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futuresecurityforumpage',
            options={'verbose_name': 'Future Security Forum 2025'},
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='About Image'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='about_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='About image alternative text'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='alternate_logo',
            field=models.ForeignKey(blank=True, help_text='This will replace the New America logo at the top of the introduction / cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Alternate Logo'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='alternate_logo_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Alternate logo alternative text'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='alternate_title_image',
            field=models.ForeignKey(blank=True, help_text='This will replace the title in the introduction / cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='alternate_title_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Alternate title image alternative text'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='city',
            field=models.TextField(blank=True, default='Washington', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='directions',
            field=wagtail.fields.StreamField([('direction', wagtail.blocks.StructBlock([('transportation_type', wagtail.blocks.CharBlock(help_text='e.g car, metro, taxi')), ('directions', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='host_organization',
            field=models.TextField(blank=True, default='New America', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='hotel_city',
            field=models.TextField(blank=True, default='Washington', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='hotel_details',
            field=wagtail.fields.RichTextField(blank=True, help_text='must be filled for header and section to appear', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='hotel_location_name',
            field=models.TextField(blank=True, help_text='Name of building (e.g. the Kennedy Center)', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='hotel_state',
            field=models.TextField(blank=True, default='D.C.', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='hotel_street',
            field=models.TextField(blank=True, default='740 15th St NW #900', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='hotel_zipcode',
            field=models.TextField(blank=True, default='20005', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='invitation_only',
            field=models.BooleanField(default=False, help_text='This will override the RSVP link and replace it with an request for invitation'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='live_stream',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='location_name',
            field=models.TextField(blank=True, help_text='Name of building (e.g. the Kennedy Center)', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='partner_heading',
            field=models.TextField(default='Sponsors & Partners'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='partners',
            field=wagtail.fields.StreamField([('partner', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock()), ('type', wagtail.blocks.ChoiceBlock(choices=[('no_type', 'None'), ('premier_sponsor', 'Premier Sponsor'), ('sponsor', 'Sponsor'), ('media_partner', 'Media Partner'), ('recognized_partner', 'Recognized Partner')])), ('logo', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False)), ('logo_alt_text', wagtail.blocks.CharBlock(help_text='A concise description of the image for users of assistive technology.', required=False, verbose_name='Logo alternative text'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='publish_sessions',
            field=models.BooleanField(default=False, help_text='Sessions list will not show up until this is checked.'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='publish_speakers',
            field=models.BooleanField(default=False, help_text='Speakers list will not show up until this is checked.'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='rsvp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='sessions',
            field=wagtail.fields.StreamField([('days', wagtail.blocks.StructBlock([('collapsible', wagtail.blocks.BooleanBlock(default=True, help_text='Allow schedule sessions to expand and collapse', required=False)), ('day', wagtail.blocks.ChoiceBlock(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], help_text='What day of the conference is this session on?', required=False)), ('start_time', wagtail.blocks.TimeBlock(required=False)), ('end_time', wagtail.blocks.TimeBlock(required=False)), ('sessions', wagtail.blocks.StreamBlock([('session', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('start_time', wagtail.blocks.TimeBlock(required=False)), ('end_time', wagtail.blocks.TimeBlock(required=False)), ('speakers', wagtail.blocks.StreamBlock([('speaker', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=False)), ('twitter', wagtail.blocks.URLBlock(required=False)), ('title', wagtail.blocks.TextBlock(required=False))]))], required=False)), ('archived_video_link', wagtail.blocks.URLBlock(help_text='Enter youtube link after conference', required=False))]))]))], help_text='for multi-day events'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='speakers',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('person', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=True)), ('title', wagtail.blocks.TextBlock(help_text='125 character limit', max_length=125, required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', required=False)), ('image_alt_text', wagtail.blocks.CharBlock(help_text='A concise description of the image for users of assistive technology.', required=False, verbose_name='Image alternative text')), ('twitter', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='state',
            field=models.TextField(blank=True, default='D.C.', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='story_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='story_image_alt',
            field=models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Cover image alternative text'),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='street',
            field=models.TextField(blank=True, default='740 15th St NW #900', null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='venue',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('columns', wagtail.blocks.StructBlock([('left_column', wagtail.blocks.RichTextBlock()), ('right_column', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='venue_details',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='zipcode',
            field=models.TextField(blank=True, default='20005', null=True),
        ),
        migrations.AlterField(
            model_name='futuresecurityforumpage',
            name='description',
            field=wagtail.fields.RichTextField(default='Lorem Ipsum', help_text='This will be the ABOUT text'),
        ),
    ]
