# Generated by Django 3.2.18 on 2025-04-16 16:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0004_auto_20250416_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresecurityforumpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='This will be the ABOUT text', null=True),
        ),
    ]
