# Generated by Django 3.2.18 on 2025-04-16 18:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0066_homepage_lead_stories'),
        ('future_security_forum', '0005_alter_futuresecurityforumpage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futuresecurityforumpage',
            options={'verbose_name': 'Future Security Forum (DO NOT USE)'},
        ),
        migrations.CreateModel(
            name='SaveTheDatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='This will be the ABOUT text', null=True)),
                ('story_image_alt', models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Cover image alternative text')),
                ('alternate_logo_alt', models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Alternate logo alternative text')),
                ('alternate_title_image_alt', models.TextField(blank=True, default='', help_text='A concise description of the image for users of assistive technology.', verbose_name='Alternate title image alternative text')),
                ('alternate_logo', models.ForeignKey(blank=True, help_text='This will replace the New America logo at the top of the introduction / cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Alternate Logo')),
                ('alternate_title_image', models.ForeignKey(blank=True, help_text='This will replace the title in the introduction / cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage')),
                ('story_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Cover Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
