# Generated by Django 3.2.18 on 2025-04-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0007_auto_20250416_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='savethedatepage',
            name='city',
            field=models.TextField(blank=True, default='Washington', null=True),
        ),
        migrations.AddField(
            model_name='savethedatepage',
            name='location_name',
            field=models.TextField(blank=True, help_text='Name of building (e.g. the Kennedy Center)', null=True),
        ),
        migrations.AddField(
            model_name='savethedatepage',
            name='state',
            field=models.TextField(blank=True, default='D.C.', null=True),
        ),
        migrations.AddField(
            model_name='savethedatepage',
            name='street',
            field=models.TextField(blank=True, default='740 15th St NW #900', null=True),
        ),
        migrations.AddField(
            model_name='savethedatepage',
            name='zipcode',
            field=models.TextField(blank=True, default='20005', null=True),
        ),
    ]
