# Generated by Django 3.2.18 on 2025-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0008_auto_20250416_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='savethedatepage',
            name='subheading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
