# Generated by Django 3.2.18 on 2025-04-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0009_savethedatepage_subheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savethedatepage',
            name='description',
        ),
    ]
