# Generated by Django 3.2.18 on 2025-05-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0010_remove_savethedatepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='savethedatepage',
            name='rsvp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
