# Generated by Django 3.2.18 on 2025-05-05 17:02

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('future_security_forum', '0011_savethedatepage_rsvp_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savethedatepage',
            name='subheading',
        ),
        migrations.AddField(
            model_name='savethedatepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='This will be the ABOUT text', null=True),
        ),
    ]
