# Generated by Django 3.2.18 on 2025-06-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_homepage_lead_stories'),
        ('future_security_forum', '0012_auto_20250505_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresecurityforumpage',
            name='social_sharing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Social Sharing Image'),
        ),
    ]
